# Generated by Django 3.2.4 on 2021-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.png', upload_to='uploaded_images'),
        ),
    ]
