# Generated by Django 3.2.4 on 2021-06-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0002_alter_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
