# Generated by Django 3.2.4 on 2021-06-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0005_auto_20210619_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resizedimage',
            old_name='resized_image',
            new_name='image',
        ),
    ]
