# Generated by Django 3.2.4 on 2021-06-19 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0006_rename_resized_image_resizedimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resizedimage',
            old_name='image',
            new_name='resized_image',
        ),
    ]
