# Generated by Django 3.2.4 on 2021-06-19 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resizer', '0007_rename_image_resizedimage_resized_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resizedimage',
            old_name='resized_image',
            new_name='image',
        ),
    ]
