# Generated by Django 3.2.4 on 2021-06-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resizer', '0010_auto_20210620_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='None', upload_to='uploaded_images')),
            ],
        ),
        migrations.CreateModel(
            name='ResizedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='resized_images')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resizer.image')),
            ],
        ),
    ]
